// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/struct.proto

package com.google.protobuf;

/**
 * <pre>
 * `NullValue` is a singleton enumeration to represent the null value for the
 * `Value` type union.
 *  The JSON representation for `NullValue` is JSON `null`.
 * </pre>
 * <p>
 * Protobuf enum {@code google.protobuf.NullValue}
 */
public enum NullValue
        implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     * Null value.
     * </pre>
     * <p>
     * <code>NULL_VALUE = 0;</code>
     */
    NULL_VALUE(0),
    UNRECOGNIZED(-1),;

    /**
     * <pre>
     * Null value.
     * </pre>
     * <p>
     * <code>NULL_VALUE = 0;</code>
     */
    public static final int NULL_VALUE_VALUE = 0;
    private static final com.google.protobuf.Internal.EnumLiteMap<
            NullValue> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NullValue>() {
                public NullValue findValueByNumber(int number) {
                    return NullValue.forNumber(number);
                }
            };
    private final int value;

    private NullValue(int value) {
        this.value = value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static NullValue valueOf(int value) {
        return forNumber(value);
    }

    public static NullValue forNumber(int value) {
        switch (value) {
            case 0:
                return NULL_VALUE;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NullValue>
    internalGetValueMap() {
        return internalValueMap;
    }

    public final int getNumber() {
        return value;
    }

    // @@protoc_insertion_point(enum_scope:google.protobuf.NullValue)
}

