// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/source_context.proto

package com.google.protobuf;

public final class SourceContextProto {
    static {
    }

    private SourceContextProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
